version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    command: python -m bot

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
